# syntax=docker/dockerfile:1

ARG RUBY_VERSION=4.0.5
FROM ruby:${RUBY_VERSION}-slim

WORKDIR /workspace

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libyaml-dev && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY Gemfile Gemfile.lock ./
RUN bundle install

RUN gem install rubocop rubocop-rails
